### PR TITLE
Add wpo_wcpdf_pdf_filters and currency symbol fix to bulk document

### LINKED ISSUE #263: wpo_wcpdf_pdf_filters and wpo_wcpdf_html_filters are not applied to bulk document
Ticket: https://wordpress.org/support/topic/currency-symbol-error-in-bulk-invoices/

Filters added [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/255) do not take into account that the bulk document has its own `get_html()` and `get_pdf()` overrides.

### PR DESCRIPTION
**Pull request by Terminator-Barbapapa**
closes #263 

- Adds the `wpo_wcpdf_pdf_filters` filter (which was added [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/255)) to the bulk document. 
- Also fixes the currency symbol not displaying in bulk documents as mentioned in this [ticket](https://wordpress.org/support/topic/currency-symbol-error-in-bulk-invoices/).

### CODE REVIEW

File: includes/documents/class-wcpdf-bulk-document.php [hunk 1]
```diff
@@ -121,6 +130,59 @@ public function get_filename( $context = 'download', $args = array() ) {
...
+	}
+
+	protected function remove_filters( $filters ) {
+		foreach ( $filters as $filter ) {
+			$filter = $this->normalize_filter_args( $filter );
+			remove_filter( $filter['hook_name'], $filter['callback'], $filter['priority'] );
+		}
+	}
+
+	protected function normalize_filter_args( $filter ) {
```
Comment (Spreeuw) [inline includes/documents/class-wcpdf-bulk-document.php:147]: this all following functions should be removed (see previous comment)

**Review by Spreeuw — CHANGES_REQUESTED** [review]

File: includes/documents/class-wcpdf-bulk-document.php [hunk 2]
```diff
@@ -45,6 +45,8 @@ public function __construct( $document_type, $order_ids = array() ) {
 		$this->type = $document_type;
 		$this->order_ids = $order_ids;
 		$this->is_bulk = true;
+
+		add_filter( 'wpo_wcpdf_pdf_filters', array( $this, 'pdf_currency_filters' ) );
```
[the remark this answers is not in the document]
Comment (Terminator-Barbapapa) [reply includes/documents/class-wcpdf-bulk-document.php]: Fixed with https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/264/commits/b0c8d0988e545fd362c184348cdab82752d47452

File: includes/documents/class-wcpdf-bulk-document.php (hunk 1 above)
Comment (Terminator-Barbapapa) [reply includes/documents/class-wcpdf-bulk-document.php:145]: Fixed with https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/264/commits/b0c8d0988e545fd362c184348cdab82752d47452

**Review by Spreeuw — APPROVED** [review]
