### PR TITLE
Fix: Fatal error when calling `WC_Tax::get_tax_rate_classes()` on older Woo versions

### LINKED ISSUE #1266: Call to protected method WC_Tax::get_tax_rate_classes()
A customer reported the following PHP error:

```
PHP Fatal error: Uncaught Error: Call to protected method WC_Tax::get_tax_rate_classes() from context 'WPO\\IPS\\UBL\\Settings\\TaxesSettings' in /wp-content/plugins/woocommerce-pdf-invoices-packing-slips/ubl/Settings/TaxesSettings.php:34\nStack trace:
#0 /wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/Settings/SettingsUbl.php(92): WPO\\IPS\\UBL\\Settings\\TaxesSettings->output()
#1 /wp-includes/class-wp-hook.php(292): WPO\\IPS\\Settings\\SettingsUbl->output('taxes', 'd4f6d57ab0')
#2 /wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#3 /wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 /wp-content/plugins/woocommerce-pdf-invoices-packing-slips/views/settings-p in /wp-content/plugins/woocommerce-pdf-invoices-packing-slips/ubl/Settings/TaxesSettings.php on line 34, referer: https://example.com/wp-admin/admin.php?page=wpo_wcpdf_options_page
```

Do note that they are using an old version of WooCommerce: 3.8.1 (2019-11-27)

### PR DESCRIPTION
**Pull request by alexmigf**
closes #1266

### CODE REVIEW

File: ubl/Settings/TaxesSettings.php [hunk 1]
```diff
@@ -31,16 +31,35 @@ public function output(): void {
...
+		// Woo 5.2+
+		if ( is_callable( array( '\WC_Tax', 'get_tax_rate_classes' ) ) ) {
+			$rates = \WC_Tax::get_tax_rate_classes();
+			
+			foreach ( $rates as $rate ) {
+				if ( empty( $rate->slug ) ) {
+					continue;
+				}
+			
+				$formatted_rates[ $rate->slug ] = ! empty( $rate->name ) ? $rate->name : $rate->slug;
```
Comment (MohamadNateqi) [inline ubl/Settings/TaxesSettings.php:47]: Why not apply `esc_attr()` anymore?

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

File: ubl/Settings/TaxesSettings.php (hunk 1 above)
Comment (alexmigf) [reply ubl/Settings/TaxesSettings.php:47]: That should be handled in the output, and it’s already being done just below in the HTML.
