### PR TITLE
Fix: function `add_yith_product_bundles_classes()` errors

### LINKED ISSUE #836: Bug in `add_yith_product_bundles_classes()` type hints & `$item`
A few customers are reporting an issue with the type hints number 2 and 4 of the function `add_yith_product_bundles_classes()`, and the `$item` object.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #836

### CODE REVIEW

File: includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php [hunk 1]
```diff
@@ -202,33 +202,46 @@ public function add_wpc_product_bundles_classes ( $classes, $document_type, $ord
...
+		if ( ! empty( $item_id ) && is_numeric( $item_id ) ) {
+			$item_id = absint( $item_id );
+		} else {
 			return $classes;
 		}
 
-		$item = new \WC_Order_Item_Product( $item_id );
-
-		if ( ! is_callable( array( $item, 'get_product' ) ) ) {
+		if ( empty( $order ) ) {
```
Comment (MohamadNateqi) [inline includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php:222]: I think this can be removed since we have type hint for `$order`.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
