### PR TITLE
Fix: bug on historical settings not being deleted when using most current settings

### LINKED ISSUE #643: Historical settings not being deleted when using current settings
Historical settings not being deleted when using most current settings. This happens when using **Test Mode** or **Most Current Settings** (document setting) and then revert back to historical, which are still there to be used.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #643

### CODE REVIEW

File: includes/documents/abstract-wcpdf-order-document.php [hunk 1]
```diff
@@ -134,11 +134,20 @@ public function init_settings() {
...
+		$this->order_settings  = $this->get_order_settings();
 		// pdf
-		$this->settings            = $this->get_settings();
-		$this->latest_settings     = $this->get_settings( true );
+		$this->settings        = $this->get_settings();
+		$this->latest_settings = $this->get_settings( true );
+		
+		// save settings
+		$latest = $this->use_historical_settings() ? false : true;
+		$this->save_settings( $latest );
```
Comment (MohamadNateqi) [inline includes/documents/abstract-wcpdf-order-document.php:150]: I think it would be good to directly use `$this->use_historical_settings()` instead of `$latest`.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Review by MohamadNateqi — APPROVED** [review]

**Review by Terminator-Barbapapa — APPROVED** [review]
LGTM
