### PR TITLE
Fix: invoice number/date screen options bug with HPOS enabled

### LINKED ISSUE #486: Wrong screen options on order edit page with HPOS enabled
The screen options on the order edit page now display the 'Invoice number' and 'Invoice date' checkboxes, which should only show on the order list page.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #486

### CODE REVIEW

File: includes/class-wcpdf-admin.php [hunk 1]
```diff
@@ -236,6 +237,10 @@ public function add_listing_actions( $order ) {
 	 * @param array $columns shop order columns
 	 */
 	public function add_invoice_columns( $columns ) {
+		if ( OrderUtil::custom_orders_table_usage_is_enabled() && isset( $_REQUEST['page'] ) && $_REQUEST['page'] == 'wc-orders' && isset( $_REQUEST['action'] ) && $_REQUEST['action'] == 'edit' ) {
```
Comment (Terminator-Barbapapa) [inline includes/class-wcpdf-admin.php:240]: Will also need the compatibility class for users that run an older WooCommerce version.

**Review by Terminator-Barbapapa — CHANGES_REQUESTED** [review]
