### PR TITLE
Fix argument mismatch in `add_document_link_to_email`

### LINKED ISSUE #1230: Handle argument mismatch in `add_document_link_to_email`
Currently, the add_document_link_to_email() method is attached to multiple WooCommerce email-related hooks.
However, the `woocommerce_email_customer_address_section` have a different parameter signature:
```php
do_action( 'woocommerce_email_customer_address_section', $type, $order, $sent_to_admin, $plain_text );
```

This leads to incorrect argument mapping and runtime errors when the method is invoked via this hook.

<hr>

A customer reported this error:

```php
CRITICAL Uncaught TypeError: WPO\IPS\Main::add_document_link_to_email(): 
Argument #4 ($email) must be of type WC_Email, bool given, called in /var/www/vhosts/example.com/httpdocs/wp-includes/class-wp-hook.php on line 324 
and defined in /var/www/vhosts/example.com/httpdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/Main.php:1864 
```

Some third-party plugins (e.g., Woo Cart Abandonment Recovery) improperly trigger WooCommerce email hooks with invalid `$email` arguments (e.g., `true` instead of a `WC_Email` object). Although we don't cause this issue, we should defensively handle these cases with `instanceof` checks before accessing email properties to prevent crashes.

### PR DESCRIPTION
**Pull request by MohamadNateqi**
close #1230

### CODE REVIEW

File: includes/Main.php [hunk 1]
```diff
@@ -1847,21 +1847,41 @@ function handle_document_link_in_emails(): void {
 		$email_hooks = apply_filters( 'wpo_wcpdf_add_document_link_to_email_hooks', $email_hooks );
 
 		foreach ( $email_hooks as $email_hook ) {
-			add_action( $email_hook, array( $this, 'add_document_link_to_email' ), 10, 4 );
+			if ( $email_hook === 'woocommerce_email_customer_address_section' ) {
```
Comment (alexmigf) [inline includes/Main.php]:
```php
if ( 'woocommerce_email_customer_address_section' === $email_hook ) {
```

File: includes/Main.php [hunk 2]
```diff
@@ -1847,21 +1847,41 @@ function handle_document_link_in_emails(): void {
...
+	}
+
 	/**
 	 * Add document download link to the email.
 	 *
 	 * @param \WC_Abstract_Order $order
 	 * @param bool $sent_to_admin
 	 * @param bool $plain_text
-	 * @param \WC_Email $email
+	 * @param mixed|\WC_Email $email Some third-parties might send different values.
```
Comment (alexmigf) [inline includes/Main.php:1880]: Maybe `null|\WC_Email` is enough?

File: includes/Main.php [hunk 3]
```diff
@@ -1847,21 +1847,41 @@ function handle_document_link_in_emails(): void {
...
 	 *
 	 * @return void
 	 */
-	public function add_document_link_to_email( \WC_Abstract_Order $order, bool $sent_to_admin, bool $plain_text, \WC_Email $email ): void {
+	public function add_document_link_to_email( \WC_Abstract_Order $order, bool $sent_to_admin, bool $plain_text, $email ): void {
```
Comment (alexmigf) [inline includes/Main.php:1884]: `?\WC_Email`

**Review by alexmigf — CHANGES_REQUESTED** [review]

**Review by alexmigf — APPROVED** [review]
LGTM!
