### PR TITLE
Fix the delay in updating PDF Document Data

### LINKED ISSUE #1153: Improve Invoice Note Save Action
It looks like there's an issue with the **action/script order** when saving the **Invoice Note** field.

### Current order:
1. Save the note  
2. **Remove loading animation**  
3. Show success message  

### Suggested correct order:
1. Save the note  
2. **Show success message**  
3. **Remove loading animation**

### Screen recorder

https://github.com/user-attachments/assets/28d40376-1313-4ebb-a455-ef77cecd5ba5

https://github.com/user-attachments/assets/ee222777-60f1-4964-adad-bd808ac4d14f

The current flow removes the loading indicator **before confirming success**, which can confuse admins. They might think the note wasn't saved (since the field doesn't update visually) and could reload the page, potentially losing their input.

Reordering these steps will give clearer feedback and improve the admin experience.

### PR DESCRIPTION
**Pull request by MohamadNateqi**
close #1153

### CODE REVIEW

File: assets/js/order-script.js [hunk 1]
```diff
@@ -128,26 +128,31 @@ jQuery( function( $ ) {
...
-
-				// unblock ui
-				$form.unblock();
+				$form.closest('#wpo_wcpdf-data-input-box').load(
+					document.URL + ' #wpo_wcpdf-data-input-box .postbox-header, #wpo_wcpdf-data-input-box .inside',
+					function() {
+						toggle_edit_mode( $form );
+
+						const notice_type   = response.success ? 'success' : 'error';
+						const $target_filed = $( this ).find( '.wcpdf-data-fields[data-document="' + data.document + '"][data-order_id="' + data.order_id + '"]' );
```
Comment (alexmigf) [inline assets/js/order-script.js:138]: Typo.

File: assets/js/order-script.js [hunk 2]
```diff
@@ -128,26 +128,31 @@ jQuery( function( $ ) {
...
+
+						if ( $target_filed.length ) {
+							$target_filed.before(
```
Comment (alexmigf) [inline assets/js/order-script.js:141]: Maybe you could remove the previous notice before the AJAX request start.

**Review by alexmigf — CHANGES_REQUESTED** [review]

**Review by alexmigf — APPROVED** [review]
LGTM!
