### PR TITLE
Proposal email attachment not working if PRO is not installed

### LINKED ISSUE #1217: Proposal email attachment not working if PRO is not installed
[HelpScout ticket](https://secure.helpscout.net/conversation/2964863985/72512)

Currently, users that purchased the order proposal plugin and only have the free PDF plugin are not able to attach proposals in emails because the free plugin blocks them.

The related code is located in `includes\Main.php`, in the `get_documents_for_email` function:
```
// Pro not activated, only attach Invoice
if ( ! function_exists( 'WPO_WCPDF_Pro' ) && 'invoice' !== $document->get_type() ) {
	continue;
};
```

We need to allow proposals as attachments in case the customer has order proposal plugin active.

### PR DESCRIPTION
**Pull request by BrunoPavlinic98**
closes #1217

### CODE REVIEW

File: includes/Main.php [hunk 1]
```diff
@@ -285,10 +285,18 @@ public function get_documents_for_email( $email_id, $order ) {
...
-			if ( ! function_exists( 'WPO_WCPDF_Pro' ) && 'invoice' !== $document->get_type() ) {
+			/**
+			 * Filter documents for email attachment based on plugin availability.
+			 * 
+			 * - If Pro plugin is not active, only allow 'invoice' and 'proposal' document types
+			 * - 'proposal' document type is only available if the Order Proposal plugin is active
+			 * - Skip documents that don't meet these criteria
+			 */
+			if ( 
+				( ! function_exists( 'WPO_WCPDF_Pro' ) && ! in_array( $document->get_type(), array( 'invoice', 'proposal' ) ) ) ||
```
Comment (alexmigf) [inline includes/Main.php]: This doesn't seem correct to me. The Proposal is not part of the `WPO_WCPDF_Pro`.

**Review by alexmigf — CHANGES_REQUESTED** [review]

File: includes/Main.php (hunk 1 above)
Comment (BrunoPavlinic98) [reply includes/Main.php]: Now that I think about it, I think the current logic will work, but it is overly complicated without good reason. I added new code that is much simpler, and works as well.

What do you think?

File: includes/Main.php [hunk 2]
```diff
@@ -285,10 +285,10 @@ public function get_documents_for_email( $email_id, $order ) {
 		$attach_documents = array();
 
 		foreach ( $documents as $document ) {
-			// Pro not activated, only attach Invoice
-			if ( ! function_exists( 'WPO_WCPDF_Pro' ) && 'invoice' !== $document->get_type() ) {
+			// This condition skips document types that require the Pro plugin unless it's an invoice or proposal
+			if ( ! in_array( $document->get_type(), array( 'invoice', 'proposal' ) ) && ! function_exists( 'WPO_WCPDF_Pro' ) ) {
```
Comment (alexmigf) [inline includes/Main.php]: Just add `true` as the third parameter for `in_array` for strict comparison.

**Review by alexmigf — CHANGES_REQUESTED** [review]

File: includes/Main.php (hunk 2 above)
Comment (BrunoPavlinic98) [reply includes/Main.php]: True, I tend to forget that. Done and thanks!
