### PR TITLE
Fix: Invoice number race condition

### LINKED ISSUE #619: Avoid double invoice creation on race condition related with Stripe payments
Some users have reported race conditions on orders paid with Stripe, which create two PDF invoices for the same order (the first is overwritten by the second).

See: 
- https://wordpress.org/support/topic/missing-4-invoices-95-99-102-and-139/#post-17098468
- https://wordpress.org/support/topic/duplicate-invoice-ids-are-generated/#post-17049280

### PR DESCRIPTION
**Pull request by alexmigf**
closes #619 

This PR attempts to fix the race condition issue spotted using Stripe plugin.

It changes the lock time to `60` seconds, to avoid expiring before the code being finished, and now also adds a lock to the email attachment function as well, which is the primary way of getting duplicated numbers.

### CODE REVIEW

File: includes/class-wcpdf-main.php [hunk 1]
```diff
@@ -131,70 +143,80 @@ public function attach_document_to_email( $attachments, $email_id, $order, $emai
 		}
 
 		$attach_to_document_types = $this->get_documents_for_email( $email_id, $order );
+		$lock_name                = $this->lock_name . '_attach_document_to_email_' . $order_id;
```
Comment (MohamadNateqi) [inline includes/class-wcpdf-main.php:146]: Does it also need to contain the document type and maybe the output type?

Comment (alexmigf) [reply includes/class-wcpdf-main.php:146]: I added the order number to avoid having concurrent orders being processed at the same time, for example, if 2 customers are buying at the exact same time.

I don't think that the document type or the output type helps here.

Comment (alexmigf) [reply includes/class-wcpdf-main.php]: > Also, Is it better to put the if above the foreach?

Yes, maybe it's better.

**Comment by alexmigf** [comment]
@MohamadNateqi check now

**Review by MohamadNateqi — CHANGES_REQUESTED** [review]

File: includes/class-wcpdf-main.php (hunk 1 above)
Comment (alexmigf) [reply includes/class-wcpdf-main.php]: Regarding the first comment [here](https://wordpress.org/support/topic/missing-4-invoices-95-99-102-and-139/), I think we should avoid that.

Comment (MohamadNateqi) [reply includes/class-wcpdf-main.php]: Can you help me understand something here? It seems a little confusing to me.

Consider, for example, ten requests at the same time (that calls the `attach_document_to_email` method ten times). One of them passes through the `if ( $lock->lock( $this->lock_retries ) ) {`, for the other nine, since the request won't freeze here until the lock gets released, then all of them fail. Am I right?

Comment (alexmigf) [reply includes/class-wcpdf-main.php]: Well, only if there are many at the same time and the process takes too much, which seems unlikely no?

File: includes/class-wcpdf-main.php [hunk 2]
```diff
@@ -131,72 +171,82 @@ public function attach_document_to_email( $attachments, $email_id, $order, $emai
...
-					wcpdf_log_error( $e->getMessage(), 'critical', $e );
-					continue;
+						
 				}
 			}
+			
+			$lock->release();
+		
+		} else {
+			$lock->log( sprintf( 'Couldn\'t get the lock for the order ID# %s!', $email_order_id ), 'critical' );
```
Comment (MohamadNateqi) [inline includes/class-wcpdf-main.php:249]: `$email_order_id` -> `$order_id`

File: includes/class-wcpdf-main.php (hunk 1 above)
Comment (MohamadNateqi) [reply includes/class-wcpdf-main.php]: > which seems unlikely no?

Yes, I think it hardly can happen. Maybe only for big stores with lots of orders, and still unlikely.
Thanks for the explanation.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

File: includes/class-wcpdf-main.php (hunk 1 above)
Comment (alexmigf) [reply includes/class-wcpdf-main.php]: Yes, my idea is avoiding having 2 or more orders processing the attachments at the same time to avoid concurrent document creations, which should avoid issues with the numbers and assignments.

**Review by MohamadNateqi — CHANGES_REQUESTED** [review]

**Review by MohamadNateqi — APPROVED** [review]
All good!

**Review by MohamadNateqi — COMMENTED** [review]
The last commit was great.

What do you think of checking that setting here and sending an empty array if it's not checked, instead of adding that in the Semaphore class? Then the `log()` method can only check the emptiness of that property.
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/842bc343f720fcb6fb6949cb35f8edfc3a66193f/includes/class-wcpdf-main.php#L174

**Review by MohamadNateqi — APPROVED** [review]
Perfect!
