### PR TITLE
Fix: `get_header_logo_id()` return type fatal error

### LINKED ISSUE #834: get_header_logo_id(): Return value must be of type int, null returned
A customer reported the following error:

> Fatal error: WPO\WC\PDF_Invoices\Documents\Order_Document::get_header_logo_id(): Return value must be of type int, null returned

### PR DESCRIPTION
**Pull request by alexmigf**
closes #834

### CODE REVIEW

**Review by MohamadNateqi — COMMENTED** [review]
What do you think of checking the return value after applying the filter [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/835/files#diff-b4b45c08877ccc6f215e534426a81b3edd82ce371cfc3fce7420e62e279b3c1eR830) and then returning `0` if it's anything but numeric? This way we can keep the return type as `int`.

File: includes/documents/abstract-wcpdf-order-document.php [hunk 1]
```diff
@@ -817,17 +817,19 @@ public function has_header_logo() {
...
 
 		if ( ! empty( $this->settings['header_logo'] ) ) {
 			$attachment_id  = $this->get_settings_text( 'header_logo', $header_logo_id, false );
 			$header_logo_id = is_numeric( $attachment_id ) ? absint( $attachment_id ) : 0;
 		}
+		
+		$header_logo_id = apply_filters( 'wpo_wcpdf_header_logo_id', $header_logo_id, $this );
 
-		return apply_filters( 'wpo_wcpdf_header_logo_id', $header_logo_id, $this );
+		return $header_logo_id ?? 0;
```
Comment (MohamadNateqi) [inline includes/documents/abstract-wcpdf-order-document.php:832]: Would it be good also to check if the value is numeric in case the filter returns any other types?

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
