### PR TITLE
Fix: adds missing deprecated filters to document title methods

### LINKED ISSUE #879: Legacy filter is not applying on template titles methods
The legacy filters are ignored in the current template titles function like here:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/main/includes/documents/class-wcpdf-invoice.php#L54-L57

### PR DESCRIPTION
**Pull request by alexmigf**
closes #879

### CODE REVIEW

File: includes/documents/class-wcpdf-invoice.php [hunk 1]
```diff
@@ -53,29 +53,32 @@ public function storing_settings_enabled() {
 	 */
 	public function get_title() {
 		// override/not using $this->title to allow for language switching!
-		return apply_filters( 'wpo_wcpdf_document_title', __( 'Invoice', 'woocommerce-pdf-invoices-packing-slips' ), $this );
+		$title = __( 'Invoice', 'woocommerce-pdf-invoices-packing-slips' );
+		return apply_filters_deprecated( "wpo_wcpdf_{$this->slug}_title", array( $this->title, $this ), '3.8.7', 'wpo_wcpdf_document_title' );
```
Comment (MohamadNateqi) [inline includes/documents/class-wcpdf-invoice.php:57]: Is there any difference which one comes first?

Comment (alexmigf) [reply includes/documents/class-wcpdf-invoice.php]: Fixed.
