### PR TITLE
Fix :SQL interpolation issues flagged by WP Plugin Check

### LINKED ISSUE #1095: Fix SQL interpolation issues in queries
WP Plugin Check flagged direct SQL interpolation. Ensure table names use `esc_sql()` and values are properly prepared to meet WordPress security standards.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #1095

### CODE REVIEW

File: includes/Settings/SettingsDebug.php [hunk 1]
```diff
@@ -1375,7 +1375,7 @@ public function fetch_number_table_data( string $table_name, string $orderby = '
 		// query
 		$chunk_results = $wpdb->get_results( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.DirectQuery
 			$wpdb->prepare(
-				"SELECT * FROM {$data['table_name']} WHERE date BETWEEN %s AND %s ORDER BY %s %s LIMIT %d OFFSET %d",
+				"SELECT * FROM `" . esc_sql( $data['table_name'] ) . "` WHERE date BETWEEN %s AND %s ORDER BY %s %s LIMIT %d OFFSET %d",
 				$data['from'],
 				$data['to'],
 				$data['orderby'],
```
Comment (MohamadNateqi) [inline includes/Settings/SettingsDebug.php:1381]: Maybe we also need to apply `esc_sql` on parameters.

Comment (alexmigf) [reply includes/Settings/SettingsDebug.php:1381]: `wpdb->prepare()` automatically sanitizes and escapes parameter values.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
