### PR TITLE
Fix: bug created by the output of the function `wpo_wcpdf_sanitize_html_content()` being `null`

### LINKED ISSUE #785: Fatal error: Return value of Order_Document_Methods::get_billing_address() must be of the type string, null returned
A customer reported the following error:

> Fatal error: Return value of WPO\WC\PDF_Invoices\Documents\Order_Document_Methods::get_billing_address() must be of the type string, null returned

### PR DESCRIPTION
**Pull request by alexmigf**
closes #785

### CODE REVIEW

File: includes/wcpdf-functions.php [hunk 1]
```diff
@@ -585,6 +585,10 @@ function wpo_wcpdf_sanitize_html_content( string $html, string $context = '', ar
 	@$dom->loadHTML( $html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD );
 	libxml_clear_errors();
 	
+	if ( false === $dom || null === $dom ) {
```
Comment (MohamadNateqi) [inline includes/wcpdf-functions.php:588]: Can `empty()` be used?

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
