### PR TITLE
Fix: Fatal error caused by invalid option type when loading debug settings

### LINKED ISSUE #1368: Fatal error when loading plugin due to invalid option data type
<p class="editor-paragraph-block">A fatal <code class="rounded bg-custom-background-80 px-[6px] py-[1.5px] font-mono font-medium text-orange-500 border-[0.5px] border-custom-border-200" spellcheck="false">TypeError</code> occurs on some installations where an option is stored as a string instead of an array, causing the plugin to crash during initialization.</p>

### PR DESCRIPTION
**Pull request by alexmigf**
closes #1368

### CODE REVIEW

File: includes/Settings.php [hunk 1]
```diff
@@ -1240,6 +1236,21 @@ public function apply_setting_categories( array $settings_fields, array $setting
...
 		return $modified_settings_fields;
 	}
+	
+	/**
+	 * Initializes settings by loading them from the database.
+	 *
+	 * @return void
+	 */
+	private function load_settings(): void {
+		$general_settings = get_option( 'wpo_wcpdf_settings_general', array() );
```
Comment (MohamadNateqi) [inline includes/Settings.php:1246]: It might be good to get them only if the class properties are empty.

Comment (alexmigf) [reply includes/Settings.php:1246]: I think this can be used to reload those settings, right?

Comment (MohamadNateqi) [reply includes/Settings.php:1246]: Yes, good point. I was thinking of lazy-loading in case it's useful.
