### PR TITLE
Fix: Remove deprecated `finfo_close()` calls for PHP 8.5 compatibility

### LINKED ISSUE #1303: Remove deprecated finfo_close() calls for PHP 8.5 compatibility
<p class="editor-paragraph-block">In PHP 8.5, <code class="rounded bg-custom-background-80 px-[6px] py-[1.5px] font-mono font-medium text-orange-500 border-[0.5px] border-custom-border-200" spellcheck="false">finfo_close()</code> is deprecated because <code class="rounded bg-custom-background-80 px-[6px] py-[1.5px] font-mono font-medium text-orange-500 border-[0.5px] border-custom-border-200" spellcheck="false">finfo</code> resources are now objects and are automatically closed when they go out of scope.</p>

### PR DESCRIPTION
**Pull request by alexmigf**
closes #1303

### CODE REVIEW

File: wpo-ips-functions.php [hunk 1]
```diff
@@ -803,7 +803,10 @@ function wpo_wcpdf_get_image_mime_type( string $src ): string {
 
 		if ( $finfo ) {
 			$mime_type = finfo_file( $finfo, $src );
-			finfo_close( $finfo );
+			
+			if ( PHP_VERSION_ID < 80000 ) {
```
Comment (MohamadNateqi) [inline wpo-ips-functions.php]: Should it be `80500`?

Comment (alexmigf) [reply wpo-ips-functions.php]: Sorry, I forgot to update when copied. Should be `80100` because it's the version when it changed to instance.

Comment (MohamadNateqi) [reply wpo-ips-functions.php]: Yeah right, PHP 8.1, sorry.
