### PR TITLE
Fix: bug on UBL preview that forces the invoice creation

### LINKED ISSUE #631: switching between PDF & UBL tabs creates an invoice
A user has reported a bug where switching between to the UBL tab creates an invoice, regardless of the "Attach to" for the PDF invoice or the UBL invoice setting:

Screenshot 2023-10-19 162526

I have tested on the latest version and have found the same issue. You don't need to interact with the UBL settings for the invoice to be created. It also creates invoices when all of the settings except "Enable" is off.

Screenshot 2023-10-19 163044

### PR DESCRIPTION
**Pull request by alexmigf**
closes #631

### CODE REVIEW

File: includes/documents/abstract-wcpdf-order-document.php [hunk 1]
```diff
@@ -958,6 +958,9 @@ public function output_html() {
 	}
 	
 	public function preview_ubl() {
+		// get last settings
+		$this->settings = ! empty( $this->latest_settings ) ? $this->latest_settings : $this->get_settings( true );
```
Comment (MohamadNateqi) [inline includes/documents/abstract-wcpdf-order-document.php:962]: May I ask why we need to have this line?

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
I could reproduce the bug, and this PR has fixed that.

File: includes/documents/abstract-wcpdf-order-document.php (hunk 1 above)
Comment (alexmigf) [reply includes/documents/abstract-wcpdf-order-document.php:962]: To display the document with the last settings.

**Review by Terminator-Barbapapa — APPROVED** [review]
