### PR TITLE
Fallback to normal document URL structure when using Plain permalink

### LINKED ISSUE #1297: Inform the usage of the pretty link when in Plain mode
<p class="editor-paragraph-block">"Pretty link" cannot work with "Plain" mode, since plain doesn't use <code class="rounded bg-custom-background-80 px-[6px] py-[1.5px] font-mono font-medium text-orange-500 border-[0.5px] border-custom-border-200" spellcheck="false">.htaccess</code> or rewrite rules.<br>Endpoints like <code class="rounded bg-custom-background-80 px-[6px] py-[1.5px] font-mono font-medium text-orange-500 border-[0.5px] border-custom-border-200" spellcheck="false">wcpdf/invoice/...</code> that are mapped by rewrite rules won't work anymore, since WP doesn't know how to route them.</p><p class="editor-paragraph-block">We need to display a warning below the "pretty link" setting when "plain" mode is selected, and also fall back to the normal link.</p>

### PR DESCRIPTION
**Pull request by MohamadNateqi**
close #1297
Plane ID: 75

image

### CODE REVIEW

File: includes/Settings/SettingsDebug.php [hunk 1]
```diff
@@ -846,8 +846,19 @@ public function init_settings() {
 				'args'     => array(
 					'option_name' => $option_name,
 					'id'          => 'pretty_document_links',
-					'description' => __( 'Changes the document links to a prettier URL scheme.', 'woocommerce-pdf-invoices-packing-slips' ),
-				)
+					'description' =>
+						__( 'Changes the document links to a prettier URL scheme.', 'woocommerce-pdf-invoices-packing-slips' ) .
+						( empty( get_option( 'permalink_structure' ) )  // Plain permalinks
+							? '<br>' . '<strong>' . __( 'Note', 'woocommerce-pdf-invoices-packing-slips' ) . '</strong>: ' . sprintf(
```
Comment (alexmigf) [inline includes/Settings/SettingsDebug.php]: Maybe this message should be rewritten to display without checking the setting, otherwise you might miss it.
