### PR TITLE
Fix: AJAX preview loading when disabled on settings pages

### LINKED ISSUE #735: Prevent Preview from being called in certain settings tabs
Currently the PDF preview is requested in every settings tab, we should create a way to prevent that on certain tabs, for example from Pro extension tabs.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #735

### CODE REVIEW

File: assets/js/admin-script.js [hunk 1]
```diff
@@ -441,6 +448,7 @@ jQuery( function( $ ) {
 
 	// Load the Preview with AJAX
 	function ajaxLoadPreview() {
+		console.log( 'Loading preview...' );
```
Comment (MohamadNateqi) [inline assets/js/admin-script.js:451]: Would you like to keep it?

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

File: assets/js/admin-script.js (hunk 1 above)
Comment (alexmigf) [reply assets/js/admin-script.js:451]: Yes, it was intentional.
