### PR TITLE
Fix: Improve display of Shipping cost and location details in PDF totals

### LINKED ISSUE #1171: Shipping not cost printed with Pickup Location
Following the [thread here](https://wordpress.org/support/topic/price-of-local-pickup/#post-18451186), when the "Pickup Locations" is set under Woocommerce > Shipping > Local Pickup, the cost for the pickup is not printed, only the pickup location address is printed. This doesn't happen in our Premium Templates, though.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #1171

### CODE REVIEW

File: includes/Documents/OrderDocumentMethods.php [hunk 1]
```diff
@@ -959,6 +959,20 @@ public function get_woocommerce_totals() {
...
+			
+			// Local pickup specific
+			if (
+				'shipping' === $key &&
+				\wpo_ips_order_has_local_pickup_method( $this->order ) &&
+				apply_filters( 'wpo_ips_show_pickup_location_details', true, $this )
+			) {
+				$order_shipping          = $this->get_order_shipping();
+				$totals[ $key ]['value'] = sprintf(
+					'%s<p class="pickup-location-details">%s</p>',
```
Comment (MohamadNateqi) [inline includes/Documents/OrderDocumentMethods.php:971]: What do you think about wrapping all around a P tag, and having a SPAN for "pickup-location-details"?

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

File: includes/Documents/OrderDocumentMethods.php (hunk 1 above)
Comment (alexmigf) [reply includes/Documents/OrderDocumentMethods.php:971]: The first placeholder shows the default pricing, and I’d like the pickup details to appear below it. That would require adding a line break or changing the span to display as a block element, I don't see that need.

Comment (MohamadNateqi) [reply includes/Documents/OrderDocumentMethods.php:971]: Good then.
