### PR TITLE
Fix: SQL injection bug in Advanced Numbers search

### LINKED ISSUE #691: SQL injection bug in Advanced Numbers search
We have received a report that we are still vulnerable to SQL injection in the Advanced Numbers search.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #691

### CODE REVIEW

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

**Review by brualio — APPROVED** [review]
LGTM

**Review by BrunoPavlinic98 — APPROVED** [review]
LGTM!

**Review by BrunoPavlinic98 — APPROVED** [review]
LGTM!

**Review by MohamadNateqi — APPROVED** [review]
LGTM!

File: includes/views/advanced-numbers.php [hunk 1]
```diff
@@ -33,7 +33,7 @@
 		</p>
 		<p><?php _e( 'Numbers may have been assigned to orders before this.', 'woocommerce-pdf-invoices-packing-slips' ); ?></p>
 		<div class="number-search" style="text-align:right;">
-			<input type="search" id="number_search_input" name="number_search_input" value="<?php echo isset( $_REQUEST['s'] ) ? esc_attr( $_REQUEST['s'] ) : ''; ?>">
+			<input type="number" id="number_search_input" name="number_search_input" value="<?php echo isset( $_REQUEST['s'] ) ? esc_attr( $_REQUEST['s'] ) : ''; ?>">
```
Comment (brualio) [inline includes/views/advanced-numbers.php:36]: imagen

Is this behaviour intended?

Comment (alexmigf) [reply includes/views/advanced-numbers.php:36]: Yes, because we are searching for database values that are integers, so I think it helps. What do you think?

Comment (alexmigf) [reply includes/views/advanced-numbers.php:36]: I can of course add a min value to avoid that. Thanks for catching it.

**Review by brualio — APPROVED** [review]
LGTM!

**Review by MohamadNateqi — APPROVED** [review]
All good!

**Review by brualio — APPROVED** [review]
Looks good!

**Review by BrunoPavlinic98 — APPROVED** [review]
LGTM!
