### PR TITLE
Fix: the function `get_extensions_license_data` returning empty if no cached data found

### LINKED ISSUE #798: The function `get_extensions_license_data`returns empty if no cached data set
After some debugging I found that the function `get_extensions_license_data` returns empty if no cached data found. This should fix the Pro license issues found with the Cloud Storage feature.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #798

### CODE REVIEW

File: includes/settings/class-wcpdf-settings-upgrade.php [hunk 1]
```diff
@@ -283,20 +283,25 @@ public function clear_extensions_license_cache() {
 	/**
 	 * Get extensions license data
 	 *
-	 * @param  string $type    can be 'cached' or 'live'
+	 * @param  string $type can be 'cached' or 'live'
 	 * @return array
 	 */
 	public function get_extensions_license_data( $type = 'cached' ) {
```
Comment (MohamadNateqi) [inline includes/settings/class-wcpdf-settings-upgrade.php:289]: Could you also add the return type declaration?

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
